name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
        with:
          scala-cli-version: 1.8.4
      - run: scala-cli --power package src/
      - name: Publish site
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/target/docs/site
          keep_files: true
