name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - uses: VirtusLab/scala-cli-setup@main
        with:
          scala-cli-version: 1.8.4
      - run: scala-cli --power package src/
